language:
  - python
python:
  - "2.7.13"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - "pip install requests"
  - "pip install -r requirements.txt"
# command to run tests
script:
  - python dublinbikeapp/tests.py -v
